"""
4. Show the sequence of numbers that would be generated by each of the following
range expressions.
a) range (5)
b) range (3, 10)
c) range (4, 13, 3)
d) range (15, 5, -2)
e) range (5, 3)

"""
# a)
print("Sequence of number generated (a): ")
for a in range(15,5,-2):
    print(a)

# b)
print("Sequence of number generated (b): ")
for b in range(3,10):
    print(b)

# c)
print("Sequence of number generated (c): ")
for c in range(4,13,3):
    print(c)

# d)
print("Sequence of number generated (d): ")
for d in range(15,5,-2):
    print(d)

# e)
print("Sequence of number generated (e): ")
for e in range(5,3):
    print(e)
